#!/bin/bash

cd "$(dirname "$0")"

. ./env/bin/activate

if [ "$1" == "all" ]
then
	docker run -p 6379:6379 -d redis:2.8

	cd flow
	./build.sh
	./jsbuild.sh
	python manage.py collectstatic
	chmod -R a+r ./visual/static 
else 
	cd flow
	python manage.py collectstatic
fi

#python manage.py runserver 0.0.0.0:8000 #--insecure
daphne -b 0.0.0.0 -p 8000 flow.asgi:application
