# Generated by Django 2.1.7 on 2019-03-30 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0003_task'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='running',
            field=models.BooleanField(default=False),
        ),
    ]
