# Generated by Django 2.1.7 on 2019-03-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0004_task_running'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='group',
            field=models.TextField(blank=True),
        ),
    ]
