# Generated by Django 2.1.2 on 2018-11-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0002_dataset_notebook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
