# Generated by Django 2.1.2 on 2018-11-20 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0004_auto_20181120_1912'),
    ]

    operations = [
        migrations.RenameField(
            model_name='notebook',
            old_name='owners',
            new_name='authors',
        ),
    ]
