# Generated by Django 2.1.2 on 2018-11-23 10:11

from django.db import migrations, models
import visual.models


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0005_auto_20181120_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='data',
            field=models.FileField(upload_to=visual.models.directory_path),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='data',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='notebook',
            name='title',
            field=models.CharField(default='New Notebook', max_length=255),
        ),
    ]
