# Generated by Django 2.1.7 on 2019-05-02 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visual', '0006_auto_20190415_1739'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='location',
            new_name='affiliation',
        ),
    ]
