from __future__ import annotations
import numpy
__all__ = ['DataStreamlines', 'RectilinearField3D', 'integrate_3d', 'interpolate_3d']
class DataStreamlines:
    def __init__(self) -> None:
        ...
    def f(self) -> memoryview:
        ...
    def l(self) -> memoryview:
        ...
    def t(self) -> memoryview:
        ...
    def y(self) -> memoryview:
        ...
class RectilinearField3D:
    def __init__(self, arg0: str) -> None:
        ...
    def dx(self) -> int:
        ...
    def dy(self) -> int:
        ...
    def dz(self) -> int:
        ...
    def velocities(self) -> memoryview:
        ...
    def x_coords(self) -> memoryview:
        ...
    def y_coords(self) -> memoryview:
        ...
    def z_coords(self) -> memoryview:
        ...
    def info(self) -> str:
        ...
def integrate_3d(arg0: RectilinearField3D, arg1: numpy.ndarray[numpy.float32], arg2: float, arg3: float) -> DataStreamlines:
    ...
def interpolate_3d(arg0: RectilinearField3D, arg1: numpy.ndarray[numpy.float32]) -> numpy.ndarray[numpy.float32]:
    ...
