# Generated by Django 2.1.2 on 2018-11-01 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20181101_1623'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatroom',
            name='text',
        ),
        migrations.AddField(
            model_name='chatroom',
            name='name',
            field=models.TextField(default=None, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
