name: "Create Python distributions"

on:
  workflow_dispatch: {}

jobs:
  make-wheels:
    name: Make ${{ matrix.os }} wheels
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["macos-latest", "ubuntu-latest", "windows-latest"]
    steps:
      - name: "Checkout repo"
        uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: "Build wheels"
        uses: pypa/cibuildwheel@v2.9.0

      - name: Verify clean directory
        run: git diff --exit-code
        shell: bash

      - name: "Upload wheel as artifact"
        uses: actions/upload-artifact@v4
        with:
          name: artifact-${{ matrix.os }}-wheel
          path: ./wheelhouse/*.whl

  make-sdist:
    name: Make source distribution
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: "recursive"

      - name: Build SDist
        run: pipx run build --sdist

      - name: Check metadata
        run: pipx run twine check dist/*

      - uses: actions/upload-artifact@v4
        with:
          name: artifact-source-dist
          path: dist/*.tar.gz

  upload:
    name: Upload to PyPI
    needs: [make-wheels, make-sdist]
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://test.pypi.org/legacy/
      password: ${{ secrets.PYPI_TEST_TOKEN }}
    permissions:
      id-token: write
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: dist

      - name: Copy artifacts to dist/ folder
        run: |
          echo "* Downloaded artifacts:"
          ls dist/
          cd dist/
          echo "* Copying artifacts to dist/ folder:"
          find . -mindepth 2 -maxdepth 2 -type f -print -exec mv {} . \;
          echo "* Deleting empty directories:"
          find . -maxdepth 1 -type d -empty -print -exec rmdir {} +
          cd ..
          echo "* Prepared artifacts:"
          ls dist/

      - name: Publish package distributions to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
